### ISSUE TITLE
Some classes are labeled as unused although it's used on the project

### ISSUE THREAD

**Issue by personaproject** [ashe23/ProjectCleaner#50]
Hi, I found a bug that somehow AnimSequence, LevelSequence, SoundWave, SoundCue, and DataTable are labeled as "UNUSED" even though it's being used in the project.

Note:
Engine UE 4.27

**Comment by ashe23** [comment]
Hello

Can you please clarify on how exactly those assets are used in project? 
- are they used in level assets?
- are they used in source code?
- are they used in config files?
- are they used as a part of editor utility scripts?

If so, then yes it a bug, if not , then possible reason why they marked unused is because they are not used by level assets or source code or by its dependecies, and if you need those assets in project, then you should exclude those from scanning. There can be many situations where i cant really know if asset is used or not, so a bit manual tweaking required.

**Comment by personaproject** [comment]
Some assets are used in source code, and the others are on level and blueprint

**Comment by ashe23** [comment]
Assets that used in source code, are those paths are hard coded? or you somehow generating them? Can you check `Assets Indirect` tab to check if those assets appear in that list? 

I tried on my end, used simple Blueprint Actor which contains soft object path to `DataTable` asset that contains `AnimSequence` asset. Placed that in the level and its correctly detected as `used` assets.

I would appriciate a bit detailed info, so i can replicate your issue :)

**Comment by personaproject** [comment]
I'll try to recreate the issue on a new project. Maybe on Saturday on Sunday.
