### ISSUE TITLE
It's all empty, but my project actually has 24g

### ISSUE THREAD

**Issue by Junt62** [ashe23/ProjectCleaner#52]
![screenshot-20240722-110249](https://github.com/user-attachments/assets/06c13a66-d005-4566-97cc-b9eb400b620d)
![screenshot-20240722-110304](https://github.com/user-attachments/assets/6aaf759e-d58c-4c0f-86d0-5e6481385f30)

**Comment by ashe23** [comment]
I think it didnt scanned properly. Can you check if there is any error messages in `OutputLog` ?

**Comment by AngelAvellaneda** [comment]
Look into the folder "Saved", you can delete it safely.

**Comment by morness** [comment]
Hi! I just downloaded this plugin and started exploring the plugin. I'm encountering the same issue as reported here. It shows my directory structure, but everything is just 0. 

I've noticed when the plugin starts up, it makes an attempt to fixup all redirectors and a small number of files are checked out. Is having totally clean redirectors a requirement for seeing all the correct data? 

We're on a custom version of 5.4 and I installed the 5.4 version of the plugin. Once the editor loads, I just click on the little trashcan icon.

**Comment by AngelAvellaneda** [comment]
You should do a fixup redirection from de content and look the Output log to see what asset give you error and delete it manually.El 16 dic 2024 23:31, morness ***@***.***> escribió:
Hi! I just downloaded this plugin and started exploring the plugin. I'm encountering the same issue as reported here. It shows my directory structure, but everything is just 0.
I've noticed when the plugin starts up, it makes an attempt to fixup all redirectors and a small number of files are checked out. Is having totally clean redirectors a requirement for seeing all the correct data?
We're on a custom version of 5.4 and I installed the 5.4 version of the plugin. Once the editor loads, I just click on the little trashcan icon.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

El 16 dic 2024 23:31, morness ***@***.***> escribió:
Hi! I just downloaded this plugin and started exploring the plugin. I'm encountering the same issue as reported here. It shows my directory structure, but everything is just 0.
I've noticed when the plugin starts up, it makes an attempt to fixup all redirectors and a small number of files are checked out. Is having totally clean redirectors a requirement for seeing all the correct data?
We're on a custom version of 5.4 and I installed the 5.4 version of the plugin. Once the editor loads, I just click on the little trashcan icon.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

El 16 dic 2024 23:31, morness ***@***.***> escribió:
Hi! I just downloaded this plugin and started exploring the plugin. I'm encountering the same issue as reported here. It shows my directory structure, but everything is just 0.
I've noticed when the plugin starts up, it makes an attempt to fixup all redirectors and a small number of files are checked out. Is having totally clean redirectors a requirement for seeing all the correct data?
We're on a custom version of 5.4 and I installed the 5.4 version of the plugin. Once the editor loads, I just click on the little trashcan icon.

**Comment by ashe23** [comment]
Hello @morness 
Yes, fixing up redirectors is mandatory before any cleanup operation. Even engine recommend you to perform this operation after moving/renaming assets, but most of the time artists and developers are forgetting to do so and later you will have some real problems. So in plugin I tried to automate this process.

Regarding 0 size, honestly I couldnt reproduce this issue, but maybe its because you using custom engine version, and if you altered some engine code its possible that it might not work correctly. I tested only on original epic versions. Also if you have 0 stats when engine loads, its ok its just means you just need to click "Scan Project" button one more time, engine just cached tab data when you closed editor with ProjectCleaner tab opened.

**Comment by AngelAvellaneda** [comment]
I learned the hard way haha, thanks ashe23 for all your work!El 17 dic 2024 7:00, Ashot Barkhudaryan ***@***.***> escribió:
Hello @morness
Yes, fixing up redirectors is mandatory before any cleanup operation. Even engine recommend you to perform this operation after moving/renaming assets, but most of the time artists and developers are forgetting to do so and later you will have some real problems. So in plugin I tried to automate this process.
Regarding 0 size, honestly I couldnt reproduce this issue, but maybe its because you using custom engine version, and if you altered some engine code its possible that it might not work correctly. I tested only on original epic versions. Also if you have 0 stats when engine loads, its ok its just means you just need to click "Scan Project" button one more time, engine just cached tab data when you closed editor with ProjectCleaner tab opened.

**Comment by ashe23** [comment]
@AngelAvellaneda glad to be helpful :)

**Comment by morness** [comment]
Yep got it working. There were some challenging redirectors to fix. Our company has some P4 checkin policies. Some of the assets that were problematic were collections. The engine attempts to auto submit those on save (there's an editor config for that), but even turning that off, there are situations where the engine still tries to auto submit them anyways, and when it fails, it reverts the CL. So I temporarily modified the engine to not do that and got through those. Tool looks amazing!

**Comment by Not4coding** [comment]
I used version 5.1.1, also got the 0 error, I looked at the log and manually fixed the log showing the error of the redirector, but finally there is still an error, in the picture, the log shows the error, but I can not find the corresponding redirector. In addition, I would like to ask what is the meaning of what Could not be deleted in the log
<img width="1280" alt="Snipaste_2024-12-29_09-27-12" src="https://github.com/user-attachments/assets/40d5e12c-acb9-47e6-ba43-839cba4793e2" />

**Comment by AngelAvellaneda** [comment]
I would try to rename the assets which are sending the messageEl 29 dic 2024 2:45, Not4coding ***@***.***> escribió:
I used version 5.1.1, also got the 0 error, I looked at the log and manually fixed the log showing the error of the redirector, but finally there is still an error, in the picture, the log shows the error, but I can not find the corresponding redirector. In addition, I would like to ask what is the meaning of what Could not be deleted in the log
Snipaste_2024-12-29_09-27-12.png (view on web)

**Comment by ashe23** [comment]
Hello @Not4coding 
`Could not delete` message actually pops when engine tries to fixup redirectors and failed to do so. But is not like regular redirectors that you can see via `ContentBrowser` filters its more like leftover redirectors . Why they are arise I cant say for sure, but i notice this happens when you migrating project to newer version without fixing up redirectors in old version. Thats one possibility there maybe other reasons i am not aware.

I actually looked in source code of engine there is this part in `Engine/Source/Editor/UnrealEd/Private/ObjectTools.cpp`
on line 2824 in function `DeleteObjects`
```cpp
if ( !DeleteModel->DoDelete() )
{
	UE_LOG(LogUObjectGlobals, Warning, TEXT("Could not delete"));

	//@todo ndarnell explain why the delete failed?  Maybe we should show the delete UI
	// when this fails?
}

return DeleteModel->GetDeletedObjectCount();
```

As you can see there is some TODO that engine developers didnt fix and that is what causing that message to pop and later causing this issues. I reported this problem long time ago when i was using v4.23 if i am correct, but seems they ignoring this problem, because its still exists in 5.5 version :(

In your case i guess you can try to rename as @AngelAvellaneda suggested or duplicate asset and delete old asset by replacing references with newly duplicated asset and then fixup redirectors.

Here is short video on how I do it.
[Redirectors Fix](https://youtu.be/viNskLk7nbc)

**Comment by Not4coding** [comment]
I checked the video you posted, and the issue was resolved after several saves and restarts. Really appreciate your help, thank you. You are my savior. I did migrate project from 5.1.0 to 5.1.1
<img width="1280" alt="Snipaste_2024-12-29_22-46-35" src="https://github.com/user-attachments/assets/1dc4cbc6-b844-4152-b10e-668ca368b4a9" />

**Comment by ashe23** [comment]
@Not4coding No problem. Happy to help :)
